version: "3.2"

services:

  functions-cgn-merchant:
    image: functions-cgn-merchant:v2.0.0
    build:
      context: ./
      dockerfile: docker/functions/Dockerfile
    env_file: 
      - .env
    environment:
      - languageWorkers__node__arguments=--inspect=0.0.0.0:5858
    working_dir: /usr/src/app
    ports:
      - "7071:7071"
      - "5858:5858"
    networks:
      - io-fn
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.functions-cgn-merchant.rule=Host(`localhost`)"
      - "traefik.http.routers.functions-cgn-merchant.entrypoints=web"
      - "traefik.http.services.functions-cgn-merchant.loadbalancer.server.port=7071"

      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.x-user-id=unused"
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.x-user-groups=${REQ_USER_GROUPS}"
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.x-subscription-id=${REQ_SERVICE_ID}"
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.x-user-email=${SERVICE_EMAIL}"
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.x-user-note=unused"
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.x-functions-key=unused"

      # apply middleware to route
      - "traefik.http.routers.functions.middlewares=testHeader"

  traefik:
    image: traefik:v2.0
    command: |-
      --entrypoints.web.address=:80
      --providers.docker=true
      --providers.docker.network=io-fn
      --log.level=ERROR
    env_file:
      - .env
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    networks:
      - io-fn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: redis-cgn
    image: wodby/redis:3.2-2.1.5
    ports:
      - "6379:6379"
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
    networks:
      - io-fn
networks:
  io-fn:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
